apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1tv0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1tv0
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1tv0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1tv0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1tv0
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fsox-tenant/rhtap-demo-app/hacbs-test-project-1tv0@sha256:52abec87e3334ecbf7f76d79f69718739ff1ad731f75c5d8f429f56d3ea02cec
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
